version: "2"
services:
  influxdb:
    container_name: influxdb
    image: influxdb:1.0.2
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes:
      - ./influxdb:/var/lib/influxdb
    restart: always

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    links:
      - influxdb
    volumes:
      - ./datasources:/etc/grafana/provisioning/datasources
      - ./dashboards/VmMetricsDashboard.yaml:/etc/grafana/provisioning/dashboards/VmMetricsDashboard.yaml
      - ./dashboards/GrafanaDashBoard.json:/var/lib/grafana/dashboards/GrafanaDashBoard.json
    restart: always

  telegraf:
    container_name: telegraf
    image: telegraf
    network_mode: "host"
    volumes:
      - ./config/telegraf.conf:/etc/telegraf/telegraf.conf
    restart: always